### ISSUE TITLE
Add more info to IP location.

### ISSUE THREAD

**Issue by ohaddahan** [block-mesh/block-mesh-monorepo#15]
1. https://ipwhois.io/documentation#endpoint
2. https://ip-api.com/docs/api:json
3. https://ipapi.co/
4. https://ipwhois.io/documentation
5. https://ipbase.com/
6. https://crates.io/crates/axum-client-ip
7. https://github.com/oschwald/maxminddb-rust/blob/main/examples/lookup.rs
8. https://crates.io/crates/ipinfo
9. https://crates.io/crates/ip2location
10. https://crates.io/crates/maxminddb
11. https://crates.io/crates/ipgeolocate

**Comment by NikolaiT** [comment]
You forgot the free geolocation database: https://ipapi.is/geolocation.html

**Comment by ohaddahan** [comment]
> You forgot the free geolocation database: https://ipapi.is/geolocation.html

This repo went public couple of hours ago, that was fast :)

**Comment by ohaddahan** [comment]
@NikolaiT can you provide more details on your response? What is mandatory? Optional, structure? etc.

I started a very simplified version of a `rust` API for your site : https://github.com/block-mesh/block-mesh-monorepo/pull/19/files , but ideally should be much more structured.

They did some of it for theirs https://github.com/ipinfo/rust/blob/master/src/api.rs#L24
