### ISSUE TITLE
Usage Flow - v0

### ISSUE THREAD

**Issue by ohaddahan** [block-mesh/block-mesh-monorepo#27]
# Initialization Flow
## Provider Node
1. Load local keys.
2. Ping `cloudflare-worker-ip-data` to get `IP` data.
3. Create or update `on-chain` `ProviderNode` account.

## Client Node
1. Load local keys.
2. Query network (`off` /`on` `chain`) to find `provider-nodes`.
3. Purchase an `ApiToken` for usage.

## BlockMesh Server
1. Periodically ping provider-node to check aliveness and update on-chain data accordingly.

# Usage Flow
1. `client-node` `POST` to the register endpoint of a `provider-node` with `{ pubkey, nonce, signed_message, api_token }`.
2. `provider-node` will authenticate `nonce` / `signed_messaged` / `pubkey` , and will verify `on-chain` that `api_token` is valid.
3. On each request the `client-node` adds the authentication header `{ pubkey, nonce, signed_message, api_token }`.
4. Both parties will register usage locally.
5. After a period of `time`/`bandwidth`/`event` based, both `client-node` and `provider-node` need to report `on-chain` and call `sync_token_usage` , if there is a mismatch the `dispute` field will mark it and one of the sides may stop respecting this `api_token` until resolved.

# Open Questions
1. How to do provider-node discovery, fully on / off chain.
2. Should we keep provider-node IP addresses public on-chain.

**Comment by ohaddahan** [comment]
> # Initialization Flow
> **User Setup and Authentication** The user generates a **local key** (as his private key using two steps authentication with SMS or Apple ID ...) for secure authentication.
> 
> This Authentication Private key is saved on his computer and connected to his wallet to pay/recv $BMESH
> 
> The Mesh Network Formation:
> 
> * I don't want us to have a "server farm" to maintain the network -> we should only handle the signaling and payments
> 
> So, it should be working something like this: **The VPN node joins the mesh network.** Each Node dynamically connect to each other via smart contracts define rules for session creation, data exchange, and updates based on the AI module we will load to client computer (replace a list of rules like ping time, trace route, etc. the AI machine will take all these info into account and find the best one for your needs) This is creating a decentralized architecture (for us it's a virtual zero cost on daily bases). Each Node maintain lists of other nodes it's connected to as a provider (we should allow multiple connections to a single node) for example i have 1GB fiber internet i can provide service to more then a single client (in case there is a need for it)
> 
> ## Provider Node
> 1. Client Node Load local keys.
> 2. Client node create or update `on-chain` `ProviderNode` account.
> 3. The user initiates a request to a Cloudflare worker that provides IP metadata.
>    The worker responds with information about end-node IPs (e.g., geolocation, latency).
> 4. The Client "CONNECT" to the VPN end-node using the Token he got from the smart contract then both establish a secure session.
> 5. Once the session is created, both the client (user) and the node provider update the blockchain contract.
> 6. The contract records session parameters, such as start time, Time To Live, Bandwidth in Token (the 100MB example we use all the time) and participating nodes (some time we many want to have primary node with 90% and backup node with 10% of data usage to make sure in case of broken internet link the session will continue without any "ping" lost.
> 
> Now we have P2P comminucation something like this:
> 
> MyIP connected to PrimaryNode 90% of the trafic MyIP connected to BackupNode 10% of the trafic ... Both connection link are always on (while data credit points are avilable)
> 
> ## Client Node
> 1. Load local keys.
> 2. Query network (`off` /`on` `chain`) to find `provider-nodes`.
>    _The client node "**Post**" request for node **on chain**_
> 3. Purchase an `ApiToken` for usage. --> this part i still don't know how this smart contracts are working
> 
> ## BlockMesh Server
> 1. Periodically/Data usage trigger (e.g., every 5-10MB of traffic)  ping `provider-node` to check aliveness and update `on-chain` data accordingly.
> 
> # Usage Flow
> 1. `client-node` `POST` to the `register` endpoint of a `provider-node` with `{ pubkey, nonce, signed_message, api_token }`.
> 2. `provider-node` will authenticate `nonce` / `signed_messaged` / `pubkey` , and will verify `on-chain` that `api_token` is valid.
> 3. On each request the `client-node` adds the authentication header `{ pubkey, nonce, signed_message, api_token }`.
> 4. Both parties will register usage locally.
> 5. After a period of time/bandwidth/event based, both `client-node` and `provider-node` need to report `on-chain` and call `sync_token_usage` , if there is a mismatch the `dispute` field will mark it and one of the sides may stop respecting this `api_token` until resolved.
> 
> # Open Questions
> 1. How to do `provider-node` discovery, fully `on` / `off` chain.
> 2. Should we keep `provider-node` `IP` addresses public `on-chain`.

@roiedahan version

**Comment by roiedahan** [comment]
see attached flow
[BMesh.drawio.pdf](https://github.com/block-mesh/block-mesh-monorepo/files/14623934/BMesh.drawio.pdf)

**Comment by ohaddahan** [comment]
# Plan for demo

# Proxy-Endpoint
1. On startup, registers on-chain.
2. Looks for Proxy-Masters on-chain.
3. Connect to one.

# Proxy-Master
1. On startup, registers on-chain.
2. Wait for clients.

# Client
1. On startup, registers on-chain.
2. Looks for Proxy-Masters on-chain.
3. Submit request to Proxy-Master.

For demo purposes - all payment etc. aren't needed, after each request each participant will write a memo on chain.
