### ISSUE TITLE
Login Failure with Correct Account Details

### ISSUE THREAD

**Issue by Dedenwrg** [block-mesh/block-mesh-monorepo#665]
**Description:**
Attempting to log in with `blockmesh-cli` results in an error, even though the credentials used are correct and the account is registered.

**Error Message:**
```plaintext
blockmesh-cli[668895]: 2024-10-31T15:55:44.604624Z ERROR blockmesh_cli::login_mode: Failed to login, did you register on https://app.blockmesh.xyz/register ?
```

**Steps to Reproduce:**
1. Execute the following command with correct login credentials:
   ```bash
   blockmesh-cli login --email 'my_email@example.com' --password 'my_password'
   ```
   or
   ```bash
   blockmesh-cli login --email my_email@example.com --password my_password
   ```
2. Observe the error message above, which suggests a failure despite valid credentials.

**Expected Behavior:**
The CLI should log in successfully when provided with valid credentials.

**Actual Behavior:**
The CLI consistently returns a login error and suggests registering, even though the account is already registered.

**Environment:**
- OS: Ubuntu 22.04.5 LTS
- `blockmesh-cli` version: v0.0.317

**Additional Context:**
I verified the account credentials on the web portal, confirming they are correct and active.

**Comment by ohaddahan** [comment]
> **Description:** Attempting to log in with `blockmesh-cli` results in an error, even though the credentials used are correct and the account is registered.
> 
> **Error Message:**
> 
> ```
> blockmesh-cli[668895]: 2024-10-31T15:55:44.604624Z ERROR blockmesh_cli::login_mode: Failed to login, did you register on https://app.blockmesh.xyz/register ?
> ```
> 
> **Steps to Reproduce:**
> 
> 1. Execute the following command with correct login credentials:
>    ```shell
>    blockmesh-cli login --email 'my_email@example.com' --password 'my_password'
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    or
>    ```shell
>    blockmesh-cli login --email my_email@example.com --password my_password
>    ```
> 2. Observe the error message above, which suggests a failure despite valid credentials.
> 
> **Expected Behavior:** The CLI should log in successfully when provided with valid credentials.
> 
> **Actual Behavior:** The CLI consistently returns a login error and suggests registering, even though the account is already registered.
> 
> **Environment:**
> 
> * OS: Ubuntu 22.04.5 LTS
> * `blockmesh-cli` version: v0.0.317
> 
> **Additional Context:** I verified the account credentials on the web portal, confirming they are correct and active.

VPS are blocked due to abuse by users.
You can run the CLI from your home network.
