### ISSUE TITLE
Error Login with cli

### ISSUE THREAD

**Issue by dwisyafriadi2** [block-mesh/block-mesh-monorepo#723]
Hello developer team. I would like to ask why I am getting this error. Even though if I log in on the website there is no problem. 
![Screenshot 2024-11-08 144329](https://github.com/user-attachments/assets/276b7d40-2fd0-4a0e-9b65-2e8f39fe5cbc)

**Comment by ohaddahan** [comment]
This isn't an issue for GitHub.
