### ISSUE TITLE
Run the block-mesh-monorepo

### ISSUE THREAD

**Issue by lidongxin112** [block-mesh/block-mesh-monorepo#751]
I use docker run the block-mesh-monorepo-Cli have a proplem 
![image](https://github.com/user-attachments/assets/8139613a-cd86-49bf-a777-ec9afdbaa3d1)
i get the response error 
I do not konw what happened 
thanks for your heko

**Comment by ohaddahan** [comment]
https://blockmesh.atlassian.net/servicedesk/customer/portals for help tickets
