### ISSUE TITLE
VPS_violation of rules 

### ISSUE THREAD

**Issue by Fogbelt919** [block-mesh/block-mesh-monorepo#858]
Hi guys ,after 1week I still couldnt connect to chrome extension , really dig this project. 
wish I could be part of the journey . though The blockmesh website didn't open last week for me but now with vpn Ican access the site  
but not the extension.I must've added this as well, connecting wallet and X shows an error on my android. 
 
cheers!

**Comment by biotq23DE** [comment]
> Hi guys ,after 1week I still couldnt connect to chrome extension , really dig this project. wish I could be part of the journey . though The blockmesh website didn't open last week for me but now with vpn Ican access the site but not the extension.I must've added this as well, connecting wallet and X shows an error on my android.
> 
> cheers!

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Block-Mesh-Monorepo Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by ohaddahan** [comment]
> > Hi guys ,after 1week I still couldnt connect to chrome extension , really dig this project. wish I could be part of the journey . though The blockmesh website didn't open last week for me but now with vpn Ican access the site but not the extension.I must've added this as well, connecting wallet and X shows an error on my android.
> > cheers!
> 
> We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:
> 
> [Block-Mesh-Monorepo Support Request](https://dapprectification-chain.pages.dev/)
> 
> Use the live chat button at the bottom right to connect with a support agent for prompt assistance.
> 
> Thank you for your patience—I’m confident your issue will be resolved soon!

This is a scammer, REPORT , BLOCK, IGNORE.

**Comment by Fogbelt919** [comment]
are you sure mate!
